# Project: DSA FINAL PROJ
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o dof.o
LINKOBJ  = main.o dof.o
LIBS     = -L"D:/others/SOFTWARES/Dev-Cpp/TDM-GCC-64/lib" -L"D:/others/SOFTWARES/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/others/SOFTWARES/Dev-Cpp/TDM-GCC-64/include" -I"D:/others/SOFTWARES/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/others/SOFTWARES/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/others/SOFTWARES/Dev-Cpp/TDM-GCC-64/include" -I"D:/others/SOFTWARES/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/others/SOFTWARES/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/others/SOFTWARES/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "DSA FINAL PROJ.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\others\SOFTWARES\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

dof.o: dof.cpp
	$(CPP) -c dof.cpp -o dof.o $(CXXFLAGS)
